### ISSUE TITLE
docker-php-ext-enable not find

### ISSUE THREAD

**Issue by charlesyq** [bravist/php-cli-alpine-aliyun-app#1]
请问下  我加新的扩展的时候 用docker-php-ext-enable  报错了
`/bin/sh: docker-php-ext-enable: not found`
该如何解决

**Comment by huiyonghkw** [comment]
我的包是基于Alpine 原生安装，并未提供docker-php-ext-enable 模块，你说的这个应该是官网推荐，建议去官方包搜索
